name: Trigger Issues to TestLink

on:
  issues:
    types: [opened]

jobs:
  call-central-workflow:
    uses: HritikG/Github-actions/.github/workflows/fetchIssueDetails.yaml@master
    with:
      issue_number: ${{ github.event.issue.number }}
      issue_title: ${{ github.event.issue.title }}
      issue_body: ${{ github.event.issue.body }}
      issue_author: ${{ github.event.issue.user.login }}
      folder_id: "138887"   # 👈 repo-specific folder
    secrets: inherit
